name: update v2ray binary
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
  schedule:
      - cron: "0 1 5 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run update script
        run: |
            cd v2ray_binary
            bash ./update_bin.sh
        shell: bash

      - name: Commit file changes
        run: |
          if [ -n "$(git status -s)" ]; then
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -am "Auto update v2ray_binary by github actions." v2ray_binary/*
            git push
          else
            echo "No modifications."
          fi
